# docker-compose.yml
version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx_base_conf:/etc/nginx/conf.d
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7-fpm
    volumes:
      - ./public:/usr/share/nginx/html
