# docker-compose.yml
version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7-fpm
    volumes:
      - ./public:/usr/share/nginx/html
